spring.datasource.url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/Meshkovo?serverTimezone=UTC}
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true
server.port: ${PORT:8080}
spring.thymeleaf.suffix: .html

#logging.level.org.springframework.web: DEBUG

spring.mail.host: smtp.gmail.com
spring.mail.username: gmeshkovoapp1977@gmail.com
spring.mail.password: 'phil03081977'
spring.mail.port: 587
spring.mail.protocol: smtp

mail.debug: true